on:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Send email
      uses: devellany/send-mail@v1.0.2
      with:
          host: smtp.google.com
          account: ${{secrets.SECRET_EMAIL}}
          password: ${{secrets.SECRET_PASSWORD}}
          sender: devellany
          from: ${{secrets.SECRET_EMAIL}}
          subject: Temporary line of text
          body: file://linesofcode.txt
          attachments: '[{"path":"linesofcode.txt"}]'
          to: devellany@gmail.com
